# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  copyToDir:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
      - uses: appleboy/ssh-action@v0.1.3
        name: Deploy to Digital Ocean droplet via SSH action
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEYPASSWORD }}
          envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,COMMAND
          script: |
            echo "pulling image"
            cd /var/www/newhtml
            git pull origin main

